language: objective-c
os: osx

env:
  global:
    - XCODE_WORKSPACE=FacebookSDK.xcworkspace
    - secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=

stages:
  - name: test
    if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: tag
    if: '! tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/'
  - name: release
    if: tag =~ /^v([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)\.([0-9]{1}|[1-9][0-9]+)($|[-+][0-9A-Za-z+.-]+$)/

jobs:
  include:
    - name: Xcode - iOS 12.0
      osx_image: xcode10.1
      env:
        - XCODE_SDK=iphonesimulator12.1
        - XCODE_SCHEME=BuildAllKits
    - name: Xcode - tvOS 12.0
      osx_image: xcode10.1
      env:
        - XCODE_SDK=appletvsimulator12.1
        - XCODE_SCHEME=BuildAllKits_TV
    - name: Xcode - iOS 11.4
      osx_image: xcode9.4
      env:
        - XCODE_SDK=iphonesimulator11.4
        - XCODE_SCHEME=BuildAllKits
    - name: Carthage - Xcode 10.1
      osx_image: xcode10.1
      if: tag IS blank
    - stage: tag
      name: Tag Version
      osx_image: xcode10.1
      script: sh scripts/run.sh tag-push-current-version
    - stage: release
      name: GitHub
      osx_image: xcode10.1
      script: sh scripts/run.sh build carthage --archive
      deploy:
        - provider: releases
          skip_cleanup: true
          api_key:
            secure: vjVOdxnuHnkDiPXoddLycTQ2WwbYudHU53xbaz86Su0J+xTSNDmxmd2GFn45EMn5BixwVzTnLWhDg7EvNvQhHWDAuHUaK7X/KXoR41s3PzlucWtxczxxt3eIRtk7U4y22tSwr/r1cl6Q2QM5IK8ICZshhSyiHHEz/EAaodcJkUE=
          file: Carthage/Release/*
          file_glob: true
          on:
            repo: facebook/facebook-objc-sdk
        - provider: script
          script: sh scripts/run.sh release cocoapods --allow-warnings
          on:
            repo: facebook/facebook-objc-sdk

before_install:
  - brew update

install:
  - bundle install
  - brew bundle

script:
  - BUILD_TYPE=$(echo "$TRAVIS_JOB_NAME" | awk '{print $1}' | tr '[:upper:]' '[:lower:]')
  - sh scripts/run.sh build $BUILD_TYPE $XCODE_WORKSPACE $XCODE_SDK $XCODE_SCHEME

notifications: # set notification options
  email:
    on_success: change
    on_failure: always
    recipients:
      - codytwinton@fb.com
  # Enable webhooks later
  # webhooks:
  # on_failure: always

after_deploy:
  - echo "Did deploy"
